[package]
name = "PayPost"
version = "1.0.0"
authors = ["PayPost Team"]

[addresses]
PayPost = "_"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
PayPost = "0xa74c3b75410a0681f854cfe2b869a3cd6b959d7dbe551aef4781c6a3ff3aa8dd"