[package]
name = "PayPost"
version = "1.0.0"
authors = ["PayPost Team"]

[addresses]
PayPost = "0xa74c3b75410a0681f854cfe2b869a3cd6b959d7dbe551aef4781c6a3ff3aa8dd"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-node-v1.8.0" }

[dev-addresses]
PayPost = "0x1"

[dev-dependencies]